version: '3'
services:
  mysql:
    image: mysql
    container_name: spit-db
    environment:
      MYSQL_ROOT_PASSWORD: database
      MYSQL_DATABASE: spit-db
    ports:
      - "3307:3306"
    volumes:
      - C:\docker\mysql-data:/var/lib/mysql
  app:
    image: openjdk:17-jdk-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spit-api
    ports:
      - "8080:8080"
    volumes:
      - ./target:/Spit.API
    depends_on:
      - mysql
    working_dir: /Spit.API
    command: ["java", "-jar", "Spit.API-0.0.1-SNAPSHOT.jar"]